/*
 * bmimage.h - bitmap image loader via picture.datatype for FriendSh3ep.
 *
 * $VER: bmimage.h 1.0 (01.07.2026)
 * Copyright (C) 2026 FriendSh3ep contributors. All rights reserved.
 *
 * Loads JPEG/PNG/BMP/IFF images using datatypes.library v44+ and
 * picture.datatype, remapped to the current screen's bitmap format.
 *
 * Lifecycle:
 *   BmImage_Init()   -- once per instance, copies file path
 *   BmImage_Load()   -- on each screen open; sets bitmap pointer
 *   BmImage_Unload() -- on iconify / screen close; frees bitmap, keeps path
 *   BmImage_Free()   -- once at teardown; frees path too
 *
 * datatypes.library v44 is opened and closed via libraryTable in friendsh3ep.c.
 */

#ifndef BMIMAGE_H
#define BMIMAGE_H

#include <exec/types.h>
#include <intuition/intuition.h>
#include <graphics/gfx.h>
#include <intuition/classusr.h>

typedef enum {
    BMIMAGE_OK             = 0,
    BMIMAGE_ERR_NO_PATH,        /* NULL or empty path given to BmImage_Init */
    BMIMAGE_ERR_NO_MEMORY,      /* AllocVec failed */
    BMIMAGE_ERR_NO_DATATYPES,   /* datatypes.library v44 not available */
    BMIMAGE_ERR_OPEN_FAILED,    /* NewDTObject returned NULL */
    BMIMAGE_ERR_NO_BITMAP,      /* layout ok but no bitmap returned */
    BMIMAGE_ERR_WRITE_FAILED    /* couldn't write the scaled BMP thumbnail to disk */
} BmImageError;

typedef struct BmImage {
    char           *filePath;   /* AllocVec'd; survives Load/Unload cycles */
    Object         *dtObject;   /* picture.datatype object; NULL when unloaded */
    struct BitMap  *bitmap;     /* owned by dtObject; valid when dtObject != NULL */
    PLANEPTR        mask;       /* owned by dtObject; transparency mask generated by
                                  * the datatype from the source's transparent color
                                  * (e.g. palette index 0) or alpha channel -- see
                                  * PDTA_MaskPlane in datatypes/pictureclass.h.
                                  * NULL if the source has no transparency. */
    UWORD           width;      /* pixel width from BitMapHeader */
    UWORD           height;     /* pixel height from BitMapHeader */
    BmImageError    error;      /* last error code; BMIMAGE_OK on success */
} BmImage;

/*
 * Initialise from a file path.  Duplicates the path string.
 * Does NOT load the image — call BmImage_Load() to do that.
 * Returns FALSE if path is NULL/empty or AllocVec fails.
 */
BOOL BmImage_Init(BmImage *img, const char *path);

/*
 * Load (or reload) the bitmap, remapped to screen's depth and format.
 * Pass screen=NULL to load raw (un-remapped) source bitmap instead.
 * img->bitmap is valid after TRUE return; img->error is set after FALSE.
 * If already loaded, unloads the previous bitmap first.
 */
BOOL BmImage_Load(BmImage *img, struct Screen *screen);

/*
 * Load (or reload) the bitmap like BmImage_Load(), but scale it first.
 * Does NOT use picture.datatype's PDTM_SCALE (it has known OS bugs), nor a
 * source-less in-memory picture.datatype object (creating one doesn't work
 * on OS3). Instead, the scaled image is materialised as a BMP file next to
 * the source (same directory, named "<filePath>.<targetWidth>x<targetHeight>.bmp")
 * and loaded from disk like any other image -- see bmimage.c's file header
 * for the full pipeline. This works regardless of screen depth (truecolor
 * or paletted).
 *
 * That BMP thumbnail is a disk cache in its own right: if it already exists
 * from a previous call with the same targetWidth/targetHeight, it's loaded
 * directly with no decode/scale work at all. It lives alongside the source
 * file, so callers whose source path is itself inside a managed cache
 * directory (see network_fs3e/fs3enet_cache.h) get thumbnail cleanup for
 * free whenever that directory is flushed.
 *
 * targetWidth x targetHeight is treated like a bounding box: the source
 * rectangle is scaled (up or down) preserving its aspect ratio so it fits
 * entirely inside that box, touching either its left/right borders or its
 * top/bottom borders (whichever axis is the tighter fit) -- same rule
 * "avatar/attachment thumbnail" callers expect from a target-box fit.
 * img->width/height are the resulting scaled size, not targetWidth/Height.
 *
 * Pass screen=NULL to load raw (un-remapped); same lifecycle/ownership as
 * BmImage_Load() otherwise. Unlike BmImage_Load(), the resulting img->mask
 * is always NULL -- BMP has no alpha/transparent-colour channel.
 */
BOOL BmImage_LoadScaled(BmImage *img, struct Screen *screen,
                         UWORD targetWidth, UWORD targetHeight);

/*
 * Dispose the datatype object and clear bitmap/dimensions.
 * File path is kept so BmImage_Load() can be called again.
 * Call on iconify or screen close.
 */
void BmImage_Unload(BmImage *img);

/*
 * Unload bitmap and free the file path.  Leaves img zeroed.
 * Call once at final teardown.
 */
void BmImage_Free(BmImage *img);

/* TRUE once BmImage_Load() has succeeded and not been Unload()/Free()'d since. */
BOOL BmImage_IsLoaded(const BmImage *img);

#endif /* BMIMAGE_H */
